---
title: Verona Interfaces Modules Metadata
format:
  html:
    from: "markdown+emoji"
---

# Introduction

The initiative "Verona Interfaces" develops specifications for computer based assessment in education in Germany. Click [here](https://verona-interfaces.github.io/) to learn more about it (German language only).

[Go to the metadata specification](verona-module-metadata.qmd)

One part of the specifications are async interfaces for modules. These modules are html pages to be used in `<iframe>` elements in frontends of web applications. One part of the specification of the modules are metadata to be placed into the website as linked data script block.

# Example

```html
<script type="application/ld+json">
    {
        "$schema": "https://raw.githubusercontent.com/verona-interfaces/metadata/master/verona-module-metadata.json",
        "id": "iqb-editor-aspect",
        "version": "2.4.9",
        "specVersion": "4.0",
        "metadataVersion": "2.0",
        "type": "editor",
        "name": [
            {
            "lang": "en",
            "value": "IQB Editor (Aspect)"
            },
            {
            "lang": "de",
            "value": "IQB-Editor (Aspect)"
            }
        ],
        "description": [
            {
            "lang": "de",
            "value": "Dieser Editor erstellt Aufgabendefinitionen in einem eigenen, JSON-Format. Anzeige- und Interaktionselemente können auf einer oder über mehreren Seiten frei oder in einem Grid positioniert werden."
            },
            {
            "lang": "en",
            "value": "This editor uses a JSON formatted unit definition. You can place elements for display or interaction purposes freely or in a grid on one or more pages."
            }
        ],
        "notSupportedFeatures": ["log-policy"],
        "maintainer": {
            "name": [
                {
                    "lang": "en",
                    "value": "IQB - Institute for Educational Quality Improvement."
                },
                {
                    "lang": "de",
                    "value": "IQB - Institut zur Qualitätsentwicklung im Bildungswesen."
                }
            ],
            "url": "https://www.iqb.hu-berlin.de",
            "email": "iqb-tbadev@hu-berlin.de"
        },
        "code": {
            "repositoryType": "git",
            "licenseType": "MIT",
            "licenseUrl": "https://opensource.org/licenses/MIT",
            "repositoryUrl": "https://github.com/iqb-berlin/verona-modules-aspect"
        }
    }
</script>
```

# Release notes

##  [2.0]{style="color: black;"}

* add metadata specification version to track changes
* remove some entries in `notSupportedFeatures` for player due to removals in player specification 5.0
* add dependencies

# License

The work of this specification is licensed under [CC0](https://creativecommons.org/public-domain/cc0/).

# About

This specification is maintained by [IQB - Institute for Educational Quality Improvement](https://www.iqb.hu-berlin.de).

To contact people, please use this [email: iqb-tbadev@hu-berlin.de](mailto:iqb-tbadev@hu-berlin.de).

You find the code of this :heart: [Quarto](https://quarto.org) based website at [GitHub](https://github.com/verona-interfaces/metadata).